name=file-sink-connector
connector.class=org.apache.kafka.connect.file.FileStreamSinkConnector
tasks.max=1
topics=user-events
file=/tmp/kafka-output.txt
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
